#!/usr/bin/env bash
set -e

TARGET=${1:=miniserve}

git clone https://github.com/PlayerG9/miniserve.git "${TARGET}"

cd "${TARGET}"

./scripts/make-install.sh

echo "
Please add the following line to your ~/.bashrc

source \"$PWD/$TARGET/scripts/bashrc\"
"
