#!/usr/bin/env bash
set -e

TARGET=${1:-fileporter}

git clone https://github.com/fileporter/fileporter.git "${TARGET}"

cd "${TARGET}"

./scripts/make-install

echo "
Please add the following line to your ~/.bashrc

source \"$PWD/scripts/bashrc\"
"
