#!/usr/bin/env python3
import sys
import hashlib

if len(sys.argv) != 2:
    print('Please provider an password with the PW="[PW]" option')
    exit(1)

hashed = hashlib.sha256(sys.argv[1].encode()).hexdigest()
print(f'hash:{hashed}')
