#!/usr/bin/env python3
import sys
import uuid
import hashlib

if len(sys.argv) != 2:
    print('Please provider an password with the PW="[PW]" option')
    exit(1)


# important: sync with src/fileporter/auth/util.py~password_hash()
hashed = hashlib.pbkdf2_hmac(
    hash_name="sha256",
    password=sys.argv[1].encode(),
    salt=str(uuid.getnode()).encode(),  # device dependent salt (same device == same salt)
    iterations=50_000,
).hex()
print(f'hash:{hashed}')
