title: miniserve
description: a documentation about miniserve
remote_theme: just-the-docs/just-the-docs@v0.4.2
#remote_theme: pmarsceill/just-the-docs

baseurl: "/miniserve" # the subpath of your site, e.g. /blog
#url: https://PlayerG9.github.io
repository: PlayerG9/miniserve # for github-metadata


logo: "/assets/logo512.png"
favicon_ico: "/assets/favicon.ico"

permalink: pretty

aux_links: # remove if you don't want this link to appear on your pages
  Source: https://github.com/PlayerG9/miniserve#readme
aux_links_new_tab: true

color_scheme: dark

enable_copy_code_button: true
search_enabled: true
heading_anchors: true


back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023 PlayerG9."

# Footer last edited timestamp
#last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/PlayerG9/miniserve" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: blue
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
